### ISSUE TITLE
Basic Computer Games

### ISSUE THREAD

**Issue by erlend-sh** [attackgoat/screen-13#7] opened 2022-02-10 16:19 UTC
Did you see this yet?
https://blog.codinghorror.com/updating-the-single-most-influential-book-of-the-basic-era/

I know it doesn’t map directly to what screen-13 is doing, but certainly in spirit it does. What might the equivalent book look like for screen-13 I wonder 🤔

**Comment by attackgoat** [comment] 2022-02-10 19:45
Yeah that's exactly the spirit of Screen 13! Also supports a good organization.

So the previous version of this library had some wickedly efficient bitmap font (and ttf!) rendering; I need to update that for v0.2 still. With that reproducing these games would be easy and fun!

At least for me the equivalent book is [this one](https://www.amazon.com/QBasic-Games-More-Fred-Sexton/dp/1565292316/ref=sr_1_1?crid=E9O8XY2H66EJ&keywords=ISBN+1-56529-231-6&qid=1644521795&s=books&sprefix=isbn+1-56529-231-6%2Cstripbooks%2C52&sr=1-1) - I recall typing these in and the "flying pigs" screensaver always stuck with me. Did you learn from any basic books?

**Comment by attackgoat** [comment] 2022-04-26 16:29
I'm closing this because my text implementation didn't make it in before the coding horror repo got a Rust version.

I've missed the only good opportunity to create `basic-bindgen` and finally have access to the power of Basic function interop in my programs.

**Closed by attackgoat** 2022-04-26 16:29 UTC
